void main(){
  //Dart dili örnek değişken tanımlamaları.
  String ilce = 'Pamukkale';
  String kita = 'Afrika';
  int faks = 9902282141042;
  int postaKodu = 41400;
  String instagram = '@Deneme';
  String calistiginBolum = 'İnsan Kaynakları';
  int urunMiktari = 58;
  String musteriSoyad = 'Duman';
  double odemeMiktari = 117.50;
  String dogumTarihi = '21.01.2001';
  double borc = 28500.50;
  String medeniHalBekar = 'Bekar';
  String medeniHalEvli = 'Evli';
  // Bu şekilde ya da bool değişken kullanarak da evli olup olmama durumunu öğrenebiliriz.
  bool evliMi = true;
  String videoYorum = 'Dying light en iyi açık dünya oyunudur.';
  String odemeSaat = '21.30';
  double eftMiktar = 210.50;
  int satilanMiktar = 400;
  String telefonModeli = 'OPPO';
  String dergiAd = 'National Geographic';
  String basimTarihi = '30.04.2024';
  int zamMiktar = 500;
  int daireSayisi = 4;
  String enlem = '37,916';
  String boylam = '29,117';
  String yemekAd = 'Kuru Fasülye';
  double urunFiyat = 56.40;
  String sirket = 'A Şirketi';
  String videoAd = 'Flutter learn';
  int  muzikSuresi = 500; //dk
  double mekanPuani = 7.0;
  String dosyaAdi = 'Flutter_dosyalari';
  String resimFormat = '.png';
  String renkKodu = '#ff0000';
  String bilgisayarModel = 'Oyuncu Bilgisayari';
  double ekranBoyutu = 4.9; //inc
  int kullanimSuresi = 4400; //dk
  double basinc = 5.0;
  String etkinlikGun = 'Pazartesi';
  String odemeGun = 'Salı';
  String yolculukCikisTarihi = '31.04.2024';
  String mahalle = 'Atatürk Mahallesi';
  String otobusHat = 'İstanbul - Kocaeli';
  int kullanilanDakika = 50;
  String kargoTakiNo = '25422561512';
  int kuponSure = 4; //Gün
  String kuponKod = 'BAHAR100';
  String faturaTarih = '01.05.2024';
}
